kind: "Namespace"
apiVersion: "v1"
metadata:
  name: "pega81"
  labels: 
    name: "pega81"
---
apiVersion: "apps/v1beta2"
kind: "StatefulSet"
metadata:
  name: "sql-pega81"
  namespace: "pega81"
  labels:
    app: "sql-pega81"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sql-pega81"
  serviceName: "sql-pega81"
  template:
    metadata:
      labels:
        app: "sql-pega81"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: "sql-pega81"
          image: "eu.gcr.io/hs-it-pega-sandbox/sqlsvr2"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 1433
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "SA_PASSWORD"
              value: "Bigp0nts"
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: "sql-pega81-v"
      volumes:
          - name: "sql-pega81-v"
            persistentVolumeClaim:
              claimName: "sql-pega81-pvc"        
---
kind: "StorageClass"
apiVersion: "storage.k8s.io/v1"
metadata:
  name: "faster"
  namespace: "pega81"
provisioner: "kubernetes.io/gce-pd"
parameters:
  type: "pd-ssd"
  zone: "europe-west1-b"
---  
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "sql-pega81-pvc"
  namespace: "pega81"
  labels:
    name: "sql-pega81"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "faster"
spec:
  storageClassName: "faster"
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sql-pega81-service"
  namespace: "pega81"
  labels:
    app: "sql-pega81"
spec:
  ports:
  - name: "1433-to-1433-tcp"
    protocol: "TCP"
    port: 1433
    targetPort: 1433
  selector:
    app: "sql-pega81"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sql-pega81-hpa"
  namespace: "pega81"
  labels:
    app: "sql-pega81"
spec:
  scaleTargetRef:
    kind: "StatefulSet"
    name: "sql-pega81"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80


      
